"""
test.py - Try one chromosome by hand, without starting a sweep.

Set CHROMOSOME below, run the file, and you get the same things a sweep builds
for each of its individuals, but for that one chromosome and without touching
the database:

    - the tree printed to the console, with its build plan and rank check
    - run/test_tree.txt   the tree drawn as it is stored on an individual
    - run/test_run.py     the runnable combination script, as generated

The test_ prefix keeps these apart from a sweep's run_NNN.py, and they land in
run/ -- a folder of their own, beside run_db/ -- because a generated script
works out where the LoRAs live as one level up from itself. The eval prompts
come from TRAINING_SET in settings.py, so they do not depend on that.

It calls the very same builders the pipeline uses (draw_trees.draw and
generate_runs.plan/render), so what you see here is exactly what you would have
got had this chromosome been drawn into a population.

Usage:
    python test.py                          # uses CHROMOSOME below
    python test.py CAT.L1.L2.w5.w2          # or pass one on the command line
"""

import os
import sys

from draw_trees import draw
from generate_population import decode
from generate_runs import build_order_block, plan, render, slot_ranks

# ---------------------------------------------------------------------------
# The individual to try. Set this and run.
# ---------------------------------------------------------------------------
CHROMOSOME = "CAT.CAT.CAT.CAT.CAT.L5.L2.L2.L1.L1.L5.w1.w5.w2.w1.w1.w4"

# Where the two output files go. Must stay one level below the project folder:
# a generated script resolves the LoRA paths relative to its own parent
# directory. A folder of its own, so nothing here can collide with a sweep's
# scripts in run_db/.
OUTPUT_DIR = "run"

_HERE = os.path.dirname(os.path.abspath(__file__))


def main():
    chromosome = " ".join(sys.argv[1:]).strip() if len(sys.argv) > 1 else CHROMOSOME

    print("chromosome: %s" % chromosome)

    # Decoding is what enforces the grammar, so a typo shows up here with a
    # message saying which symbol broke which rule.
    try:
        root, used = decode(chromosome)
    except ValueError as error:
        raise SystemExit("not a valid chromosome: %s" % error)

    tail = chromosome.split(".")[used:]
    if tail:
        print("note: %d trailing symbol(s) are not part of the tree: %s"
              % (len(tail), ".".join(tail)))

    # Ranks come from each slot's adapter_config.json; they may differ. The
    # slots themselves are LORA_SLOTS in settings.py, the same ones a sweep uses.
    out_dir = os.path.join(_HERE, OUTPUT_DIR)
    steps, final = plan(root, slot_ranks())
    broken = [step for step in steps if step.broken]

    print("\ntree")
    for line in draw(chromosome)[2:]:
        print("    %s" % line)

    print("\nbuild order (deepest first)")
    for line in build_order_block(steps):
        print(line)

    if broken:
        print("\nverdict: BLOCKED -- %s is linear with mismatched input ranks "
              "(%d vs %d); the run stops there."
              % (broken[0].name, broken[0].left[2], broken[0].right[2]))
    else:
        print("\nverdict: ok -- %d adapters, final rank %d"
              % (len(steps), steps[-1].rank))

    # --- write the two files ---
    os.makedirs(out_dir, exist_ok=True)

    tree_path = os.path.join(out_dir, "test_tree.txt")
    with open(tree_path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(draw(chromosome)) + "\n")

    script_path = os.path.join(out_dir, "test_run.py")
    with open(script_path, "w", encoding="utf-8") as handle:
        handle.write(render(
            chromosome, steps, final,
            script_name="test_run.py",
            provenance="Generated by test.py from the CHROMOSOME set in that file.",
            label="Individual (from test.py)",
        ))

    print("\nwrote %s" % tree_path)
    print("wrote %s" % script_path)
    if broken:
        print("test_run.py is written anyway, with the NOTE explaining where it stops.")


if __name__ == "__main__":
    main()
