"""
test.py - Try one chromosome by hand, without touching population.txt.

Set CHROMOSOME below, run the file, and you get the same three things the
batch tools produce, but for that one individual:

    - the tree printed to the console, with its build plan and rank check
    - test/tree.txt   the tree drawn as in trees.txt
    - test/run.py     the runnable combination script, as in run/

It calls the very same builders the batch tools use (draw_trees.draw and
generate_runs.plan/render), so what you see here is exactly what you would
have got had this chromosome been a line in population.txt.

Usage:
    python test.py                          # uses CHROMOSOME below
    python test.py CAT.L1.L2.w5.w2          # or pass one on the command line
"""

import os
import sys

from draw_trees import draw
from generate_population import decode
from generate_runs import build_notes, plan, render

# ---------------------------------------------------------------------------
# The individual to try. Set this and run.
# ---------------------------------------------------------------------------
CHROMOSOME = "CAT.SVD.LIN.L1.L2.L3.L1.w3.w3.w2.w1"

# Where tree.txt and run.py get written.
OUTPUT_DIR = "test"

_HERE = os.path.dirname(os.path.abspath(__file__))


def main():
    chromosome = " ".join(sys.argv[1:]).strip() if len(sys.argv) > 1 else CHROMOSOME

    print("chromosome: %s" % chromosome)

    # Decoding is what enforces the grammar, so a typo shows up here with a
    # message saying which symbol broke which rule.
    try:
        root, used = decode(chromosome)
    except ValueError as error:
        raise SystemExit("not a valid chromosome: %s" % error)

    tail = chromosome.split(".")[used:]
    if tail:
        print("note: %d trailing symbol(s) are not part of the tree: %s"
              % (len(tail), ".".join(tail)))

    steps, final = plan(root)
    broken = [step for step in steps if step.broken]

    print("\ntree")
    for line in draw(chromosome)[2:]:
        print("    %s" % line)

    print("\nbuild order (deepest first)")
    for line in build_notes(steps):
        print(line)

    if broken:
        print("\nverdict: BLOCKED -- %s is linear with mismatched input ranks "
              "(%d vs %d); PEFT raises ValueError there."
              % (broken[0].name, broken[0].left[2], broken[0].right[2]))
    else:
        print("\nverdict: ok -- %d adapters, final rank %d"
              % (len(steps), steps[-1].rank))

    # --- write the two files ---
    out_dir = os.path.join(_HERE, OUTPUT_DIR)
    os.makedirs(out_dir, exist_ok=True)

    tree_path = os.path.join(out_dir, "tree.txt")
    with open(tree_path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(draw(chromosome)) + "\n")

    script_path = os.path.join(out_dir, "run.py")
    with open(script_path, "w", encoding="utf-8") as handle:
        handle.write(render(
            chromosome, steps, final,
            script_name="run.py",
            provenance="Generated by test.py from the CHROMOSOME set in that file.",
            label="Individual (from test.py)",
        ))

    print("\nwrote %s" % tree_path)
    print("wrote %s" % script_path)
    if broken:
        print("run.py is written anyway, with the NOTE explaining where it stops.")


if __name__ == "__main__":
    main()
